name: Schedule Worker
on: push
#on:
  #schedule:
   # - cron: '40 16,4 * * *' #每日24点40,12点40，两个时间点执行任务
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
        
      - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/setup-python@v4 # 使用python装配器
        with:
          python-version: '3.10' # 指定python版本
          cache: 'poetry' # 设置缓存
          cache-dependency-path: '**/poetry.lock'

      - run: poetry install --without dev # 安装
      - run: poetry run python .\main.py # 执行


